### ISSUE TITLE
Print messages on screen

### ISSUE THREAD

**Issue by paulpage** [paulpage/py2048#26]
All user-facing messages are currently printed on the titlebar. This is problematic for a few reasons.

1. It's rather unintuitive and easy to miss.
2. Users of tiling window managers that hide the titlebar won't see the messages at all.
3. It doesn't allow a full screen option.

I think it would be fairly easy to write the messages in the bottom left corner of the screen, opposite the restart and help buttons.

**Comment by biggles5107** [comment]
The other problem with printing messages in the titlebar is that currently the messages are cut off on a HiDPI display under Linux. This happens because the titlebar is rendered by the window manager with the correct scaling, but the window’s contents are not.

I’m thinking that instead of having all messages (including win/lose notifications) in the status bar, we should create a blocking message in the center of the board for win/lose notifications and have “Invalid move” and “Auto mode” show up at the bottom.

We should probably also remove the score from the titlebar and find a spot for it in the status bar. This isn’t as important but would be good for UI consistency. 

From: Paul Page
Sent: Friday, January 4, 2019 7:39 PM
To: paulpage/py2048
Cc: Subscribed
Subject: [paulpage/py2048] Print messages on screen (#26)

All user-facing messages are currently printed on the titlebar. This is problematic for a few reasons.
1. It's rather unintuitive and easy to miss.
2. Users of tiling window managers that hide the titlebar won't see the messages at all.
3. It doesn't allow a full screen option.
I think it would be fairly easy to write the messages in the bottom left corner of the screen, opposite the restart and help buttons.

**Comment by biggles5107** [comment]
Working on it.

**Comment by biggles5107** [comment]
Fixed by recent commit. Finally got around to merging my branch that had code sitting in it for a good month and a half :P
